### ISSUE TITLE
JSON and vars issues

### ISSUE THREAD

**Issue by RandomFractals** [DonJayamanne/typescript-notebook#10] opened 2021-07-08 03:08 UTC
Great extension. However, I ran into a few issues with it.

1. I can't use JSON.parse to parse json data. I get an error that JSON is not found.
2. Cell vars are local? I get an error for the csvString var in my test notebook, even tho I can see csv data ouput:

see this ticket in my data table renderer repo for more info: https://github.com/RandomFractals/vscode-data-table/issues/27

![ts-json-data-notebook](https://user-images.githubusercontent.com/656833/124856096-90490300-df6f-11eb-8ab8-b85e1e86a698.png)

![csv-data-output](https://user-images.githubusercontent.com/656833/124856134-9d65f200-df6f-11eb-9fe4-e42a64ae82c5.png)

**Comment by RandomFractals** [comment] 2021-07-13 00:45
btw, I was able to put together a decent example with this extension: https://github.com/RandomFractals/vscode-data-table#typescript-notebook-example

Would be nice if `JSON.parse` worked to take it further.

**Comment by DonJayamanne** [comment] 2021-07-14 04:43
Hmm, i think this is a bug in the jupyter extension, let me check.

**Comment by DonJayamanne** [comment] 2021-07-14 05:47
Please could you check what version of tslab is installed.
`tslab --version`.
I am unable to repro the issue

**Comment by RandomFractals** [comment] 2021-07-14 13:00
I ran it with the latest tslab v1.0.15

**Comment by RandomFractals** [comment] 2021-07-14 13:58
> I am unable to repro the issue

I just tried with the latest insiders v. Same results:

![image](https://user-images.githubusercontent.com/656833/125634755-9a9918ad-8d09-410c-96ba-581d67dd0f33.png)

Version: 1.59.0-insider (user setup)
Commit: 9520f0a515e7e24802c92f885a0efb242fca3831
Date: 2021-07-14T07:15:41.024Z
Electron: 13.1.6
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0

**Comment by RandomFractals** [comment] 2021-07-14 15:33
the same results in the latest vscode stable Version: 1.58.1 (user setup)
Commit: 2aeda6b18e13c4f4f9edf6667158a6b8d408874b
Date: 2021-07-13T06:58:28.115Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0

Note that your TS cell does recognize `JSON.parse` as a valid method:

![image](https://user-images.githubusercontent.com/656833/125649549-1f1f56e8-0c4c-4ac0-a584-6a3ebabb6401.png)

**Comment by DonJayamanne** [comment] 2021-07-23 17:45
Ok, I can see similar issues at my end when dealing with arrays.
I think this is a problem with tslab (kernel).

**Comment by DonJayamanne** [comment] 2021-07-23 17:48
Closing this issue, as this is caused by the tslab kernel. Please report this issue here https://github.com/yunabe/tslab

**Closed by DonJayamanne** 2021-07-23 17:48 UTC
